"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// import { Point } from './point';
var like_component_1 = require("./like.component");
// import {LikeComponent} from './like.component';
// var point = new Point(2, 6);
// point.draw();
var component = new like_component_1.LikeComponent(12, true);
component.onClick();
console.log("Likes count: " + component.likesCount + ", isSelected: " + component.isSelected);
